### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by tenlo** [zpfz/vuepress-theme-antdocs#14]
**Describe the bug**
此问题和 另一个  [issues](https://github.com/zpfz/vuepress-theme-antdocs/issues/1)  类似，但区别在于，我为项目单独安装了vuepress，但还是跑不起来 ，控制台的错误和  [issues](https://github.com/zpfz/vuepress-theme-antdocs/issues/1)  一样

**To Reproduce**

1. 按照   [vuepress 官网](https://vuepress.vuejs.org/guide/)   的文档，建立一个可以使用的 demo目录结构
2. 安装依赖
```js
npm init -y
npm i vuepress
```

2. 按照   [antdocs 官网](https://antdocs.seeyoz.cn/guide/getting-started.html)   的指示，安装主题依赖
```js
npm i vuepress-theme-antdocs
```

3. 运行

**Expected behavior**
- 打开 http://localhost:8080/ ，页面显示空白，控制台有错误输出

**System Info**
- VuePress version: 1.5.1
- Antdocs version: 1.1.1
- Node version: 12.14.1
- npm version: 6.13.4

**相关截图**

- 依赖配置
![QQ截图20200613133411](https://user-images.githubusercontent.com/28176926/84561235-519d4500-ad7d-11ea-890c-156092e27678.png)

-  按照vuepress官网 建立的页面结构，运行的页面
![QQ截图20200613132559](https://user-images.githubusercontent.com/28176926/84561232-4f3aeb00-ad7d-11ea-9406-110ff677218a.png)

- 目录结构
![QQ截图20200613132842](https://user-images.githubusercontent.com/28176926/84561234-5104ae80-ad7d-11ea-9f9c-dba0d9d804e3.png)

- 安装主题后，页面及控制台输出
![QQ截图20200613135614](https://user-images.githubusercontent.com/28176926/84561285-b6589f80-ad7d-11ea-9006-736985c5ae64.png)

**Comment by zpfz** [comment]
为了避免手动创建 vuepress 项目导致出现各种问题，建议您使用 vuepress-creator 脚手架快速创建对应项目。
