### ISSUE TITLE
footer add ico

### ISSUE THREAD

**Issue by yekangming** [zpfz/vuepress-theme-antdocs#15]
for chinese gov something special reasons, put on record to ICP or public security department need in footer add the hyperlink and ico.

**Comment by zpfz** [comment]
Thank you for receiving your feedback. In addition to fixing the BUG of the theme, we will not upgrade the new feature of the theme for the time being.We will add your idea to 2.0, please be patient.    

Solution:   
1.Open `/node_module/vuepress-theme-antdocs/components` under the project；  
2.Find `Home.vue` file, open it and modify the following snippet that what u want:   
```html
<div :class="{ 'footer-divider': isDivider, 'footer-bottom': true }">{{ data.footer }}</div>
```

**Comment by zpfz** [comment]
Hi, bro.How's goin? I optimize the problem, add your idea in `v1.2.2`,  `v1.3.2` is a perfect version at present, you can upgrade vuepress-theme-antdocs to `v1.3.2`
