### ISSUE TITLE
能多加一些使用 Antd的案例吗

### ISSUE THREAD

**Issue by pxxyyz** [zpfz/vuepress-theme-antdocs#16]
干接触不久，希望作者能[在 Markdown 中使用 Antd](https://antdocs.seeyoz.cn/guide/using-antd.html)加入更多的案例，例如icon和表格，感激不尽:smile:

**Comment by zpfz** [comment]
其实用法和在Vue中使用方法类似，Vuepress官网有详细说明，你可以回归Vuepress文档翻翻相关资料。这里推荐使用组件形式进行调用，而不是直接在 md 文件里面写组件代码，当然，像图标这种简短的代码可以直接写在 md 文件内。

附：
Ant Design Vue 文档：https://www.antdv.com/docs/vue/introduce-cn/
VuePress 组件编写：https://vuepress.vuejs.org/guide/using-vue.html#using-components
