### ISSUE TITLE
建议修改ads的class名字改为promote

### ISSUE THREAD

**Issue by CracKerMe** [zpfz/vuepress-theme-antdocs#19]
**Is your feature request related to a problem? Please describe.**
它不是一个问题，具体表现为 当我开启了 adblock之后，ad 或者 ads的class名的dom节点都会被隐藏。

**Describe the solution you'd like**
建议修改相关关键字的 改成promote 亲测有效。。针对Ads.vue修改即可

**Describe alternatives you've considered**

**Additional context**

**Comment by zpfz** [comment]
关于开启 adblock 导致广告位被屏蔽的问题，我觉得改类名意义不是很大，因为类名默认是静态，只要用户在 adblock 添加过滤规则仍然可以达到净化广告的效果。在下个版本我们应该会优化这个问题，重新定义它存在的意义（比如：用于推广、用于广告系统接入等等）。
