### ISSUE TITLE
侧边栏怎么配置自动生成

### ISSUE THREAD

**Issue by OvedayBySnow** [zpfz/vuepress-theme-antdocs#2]
我看代码应该是满足这个条件的  你的文档好像也没有细说

**Comment by zpfz** [comment]
主题默认不带有自动生成侧边栏功能，你可以在 NpmJs 找到类似的插件，比如：vuepress-plugin-auto-sidebar。
The theme does not have an auto-sidebar generation feature by default. You can find similar plugins in NpmJs, e.g.  vuepress-plugin-auto-sidebar.

**Comment by CracKerMe** [comment]
那有考虑兼容进去么？关于这个自动生成侧边栏的功能

**Comment by zpfz** [comment]
> 那有考虑兼容进去么？关于这个自动生成侧边栏的功能

这个功能我们需要对它进一步评估，当然，我们也希望能解决掉 VuePress 有这个问题的痛点，应该会换个方式解决这个问题，但目前因为繁忙还没规划 Antdocs 下个版本的相关功能~

**Comment by CracKerMe** [comment]
> 这个功能我们需要对它进一步评估，当然，我们也希望能解决掉 VuePress 有这个问题的痛点，应该会换个方式解决这个问题，但目前因为繁忙还没规划 Antdocs 下个版本的相关功能~

当前 配合 **vuepress-plugin-auto-sidebar** 以及 
"scripts": {
    "dev": "vuepress dev docs --temp .temp",
    "build": "vuepress build docs"
  },
生成.temp的文件夹可以做到 实时hot-reload ，建议一起合并参考一下

**Comment by zpfz** [comment]
> 生成.temp的文件夹可以做到 实时hot-reload ，建议一起合并参考一下

目前 VuePress 版本的 Antdocs 主题不会考虑把它整合进去，在热处理方面还是得看尤大怎么利用 vite 来架构 vitepress，你这个问题不错，也建议你把问题反馈给尤大，直通车：[VitePress](https://github.com/vuejs/vitepress)
