### ISSUE TITLE
主题有办法添加icp备案号在底部吗？

### ISSUE THREAD

**Issue by e7no** [zpfz/vuepress-theme-antdocs#20]
类似这样
<img width="1041" alt="图片" src="https://user-images.githubusercontent.com/22765856/89122463-e577cb80-d4f9-11ea-8b44-7f73dd8a994e.png">

**Comment by zpfz** [comment]
fork一份主题文件放到项目对应文件夹里(至于放在哪里请见VuePress官网)，然后参考 #15 修改相关文件。

**Comment by zpfz** [comment]
v1.2.2版本支持添加ICP备案号了哦，时空门：[页脚](https://antdocs.seeyoz.cn/guide/extend-config.html#页脚-1-2-2)
