### ISSUE TITLE
支持最大内容宽度设定

### ISSUE THREAD

**Issue by imgradeone** [zpfz/vuepress-theme-antdocs#21]
**Is your feature request related to a problem? Please describe.**
没有相关 issue

**Describe the solution you'd like**
考虑到电脑显示屏幕太宽，而 AntDocs 内容默认显示区域基本占满整个屏幕，尤其是在禁用侧边栏后的效果特别难受。

**Describe alternatives you've considered**
其实 VuePress 默认主题就考虑到了最大内容宽度，所以效果就比较舒服。

下面是 AntDocs 主题和 VuePress 默认主题的对比图。（这里的 VuePress 默认主题预览图用的是一个 alternative，但是和官方默认主题一致）
![AntDocs](https://user-images.githubusercontent.com/30969327/94821546-435e5c00-0434-11eb-93c4-8b1d77da4f6c.png)
![VuePress 默认](https://user-images.githubusercontent.com/30969327/94821583-4e18f100-0434-11eb-8dce-7dd120b9d432.png)

**Additional context**
*无*

**Comment by zpfz** [comment]
可以用样式**媒体查询**暂时解决这个自适应问题哦。

**Comment by zpfz** [comment]
AntDocs v1.3.2 已优化这个问题，具体见：[v1.3.2](https://antdocs.vercel.app/guide/changelog.html)，感谢你的提议哈~
