### ISSUE TITLE
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

### ISSUE THREAD

**Issue by lyl340321** [zpfz/vuepress-theme-antdocs#22]
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

**Comment by zpfz** [comment]
Your issue has been closed because you did not ask questions based on the issue template.

**Comment by imgradeone** [comment]
try to downgrade `core-js` to v2

refer #5
