### ISSUE TITLE
markdown中没有Heading标签 content 被导航遮挡

### ISSUE THREAD

**Issue by exuan** [zpfz/vuepress-theme-antdocs#25]
**Describe the bug**
历史问题 markdown里没有Heading elements, index.less first-child rem设置失效

https://github.com/zpfz/vuepress-theme-antdocs/blob/master/styles/index.less#L156

建议 把 margin-top 配置到page class,跟sidebar一直
https://github.com/zpfz/vuepress-theme-antdocs/blob/master/components/Page.vue#L27

**Comment by lemos1235** [comment]
是的，换成官方主题就没事。

**Comment by zpfz** [comment]
AntDocs v1.3.2 已修复这个问题，具体见：[v1.3.2](https://antdocs.vercel.app/guide/changelog.html)
