### ISSUE TITLE
Feat: 首页主次级图标区分

### ISSUE THREAD

**Issue by imgradeone** [zpfz/vuepress-theme-antdocs#26]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
目前首页的主次级按钮都用的是 `ghost` 属性的 `a-button`，区分性较差。既然是主次级按钮，我个人认为在样式上需要有区分。因此，主按钮采用默认 `primary`，次按钮采用 `primary ghost` 的方案应该更好。

![屏幕截图(14)](https://user-images.githubusercontent.com/30969327/103341315-8e365100-4ac1-11eb-9a06-7ba85b431e8e.png)

**Describe alternatives you've considered**
(No)

**Additional context**
(empty)

**Comment by zpfz** [comment]
这个优化将会在2.0体现，因为1.x采用居中方式，不太适合你所述的方式。2.0的话，会重新对首页进行改版，让首页更加丰富~
