### ISSUE TITLE
这些样式md源码是怎么写的？看起来很美观，可以给个说明写在antdocs文档里面吗？

### ISSUE THREAD

**Issue by hoochanlon** [zpfz/vuepress-theme-antdocs#28]
更新日志的千竹节是怎么做出来的，怎样才能显示这样的提示、建议框？
![C1AAB663-2925-43AE-8CB6-AF777B5FD970](https://user-images.githubusercontent.com/35732922/110094414-c403f880-7dd6-11eb-978a-dbb8d08740aa.jpeg)

**Comment by zpfz** [comment]
> 更新日志的千竹节是怎么做出来的，怎样才能显示这样的提示、建议框？
> ![C1AAB663-2925-43AE-8CB6-AF777B5FD970](https://user-images.githubusercontent.com/35732922/110094414-c403f880-7dd6-11eb-978a-dbb8d08740aa.jpeg)
> 
> 

官方文档已开源，请自行参考(官方文档)[https://github.com/zpfz/antdcos-document/]
另外，Antdv组件使用见：https://antdv.com/
