### ISSUE TITLE
细节完善

### ISSUE THREAD

**Issue by Roy-Kid** [zpfz/vuepress-theme-antdocs#29]
markdown最好能设置成左右对齐, 现在行尾参差不齐就很难受...

另, 有一个主题叫vuepress-theme-teadoc, 可以参(zhao)考(chao)一下, 非常流畅.
我现在的文档就是用的它的主题 lammps.org.cn, 我觉得现阶段要比这个更好一些

**Comment by zpfz** [comment]
好的哈，对比一下确实是有这个问题，后期我再看看哪种优化方案好一点~

**Comment by zpfz** [comment]
晚上测试了一下，发现两端对齐效果也不是很好，特别是和英文在一起的时候都被隔开了。你说的那个效果是否也有这个问题呢？

**Comment by Roy-Kid** [comment]
确实. 我这边也是左端对齐. https://lammps.org.cn/zh/tutorial/linux/chap02.html
我也不太清楚怎么搞比较好, 等你的v2吧. 前端太难学了, 从来没见过这么难的东西... 
辛苦你了!
