### ISSUE TITLE
新版本的代码区块样式问题

### ISSUE THREAD

**Issue by vxhly** [zpfz/vuepress-theme-antdocs#31]
**Describe the bug**
开启代码的行号时，看到这边的行号样式是白色

![image](https://user-images.githubusercontent.com/17906558/117764937-d16ab280-b25f-11eb-8634-73d9d284a1ea.png)

修改样式之后有很明显的错位
![image](https://user-images.githubusercontent.com/17906558/117765049-f9f2ac80-b25f-11eb-987b-1951d55e194b.png)

**To Reproduce**

**Expected behavior**

**System Info**
- VuePress version: 1.8.2
- Antdocs version: 1.3.2
- Node version:
- OS version:

**Additional context**

**Comment by zpfz** [comment]
😄已修复了哈，最新版本1.3.4🙋
