### ISSUE TITLE
侧边栏分组的组标题可以有吗

### ISSUE THREAD

**Issue by wakaryry** [zpfz/vuepress-theme-antdocs#32]
侧边栏需要分组，需要有一个组标题用来提示以及隔断。这个应该怎么配置。
谢谢

**Comment by zpfz** [comment]
你说的是侧边栏分组功能吗？这个功能和VuePress配置一样的，详情见：[分组](https://vuepress.vuejs.org/zh/theme/default-theme-config.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E5%88%86%E7%BB%84)

**Comment by wakaryry** [comment]
谢谢。搞定了。
