### ISSUE TITLE
启动项目后报link未定义，首页无法显示

### ISSUE THREAD

**Issue by lanwp530** [zpfz/vuepress-theme-antdocs#33]
**Describe the bug**
启动应用后，应用正常启动。但是进入首页后报如下错误，link未定义页面无法正常显示：
![微信图片_20210520130543](https://user-images.githubusercontent.com/12046575/118922185-25fee380-b96c-11eb-9e25-ce227783d2c0.png)

**To Reproduce**
1. 启动应用。
2. 正常启动后访问首页

**Expected behavior**

**System Info**
- VuePress version: 1.8.2
- Antdocs version:  1.3.4
- Node version: v14.16.0
- OS version:  win10 （Microsoft Windows [版本 10.0.16299.15]）

node package.json引用依赖
```
"devDependencies": {
    "@vuepress/plugin-active-header-links": "^1.5.4",
    "@vuepress/plugin-back-to-top": "^1.5.4",
    "@vuepress/plugin-nprogress": "^1.5.4",
    "vuepress": "^1.5.4",
    "vuepress-plugin-permalink-pinyin": "^1.0.0"
  },
  "dependencies": {
    "vuepress-theme-antdocs": "^1.3.4"
  }
```
**Additional context**

**Comment by zpfz** [comment]
antdocs v1.3.4 做了一些破坏性变动，需要将首页的 README.md 中首页按钮配置进行修改，例：
```md
actionBtn:
  text: Get Started
  link: /guide/
  type: primary
  ghost: false
  size: large
preactionBtn:
  text: Playground
  link: /guide/
  type: primary
  ghost: true
  size: large
```
详情见：[首页按钮](https://antdocs.pages.dev/guide/extend-config.html#首页按钮)，另外 antdocs 近期更新详情见：[更新日志](https://antdocs.pages.dev/guide/changelog.html)。  
目前不建议使用 vuepress-creator 创建项目，请等待 vuepress-creator 更新后再使用。

**Comment by xkloveme** [comment]
缺少首页配置项导致,我提交了pr,请作者合并

**Comment by zpfz** [comment]
> 缺少首页配置项导致,我提交了pr,请作者合并

已合并更新，感谢你的PR哈！
