### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by metoyun** [zpfz/vuepress-theme-antdocs#36]
谷歌浏览器 Firefox 都有同样问题， 内存占用一直往上涨，高达8个g左右也不知道是啥问题导致的

**Comment by zpfz** [comment]
> 谷歌浏览器 Firefox 都有同样问题， 内存占用一直往上涨，高达8个g左右也不知道是啥问题导致的

经测试，目前暂未发现 antdocs 主题存在该类问题，您可以检查看看是否其他工具影响 antdocs 占用升高哈~

**Comment by metoyun** [comment]
> > 谷歌浏览器Firefox自带的问题，内存占用一直都一样，高达8个左右也不知道是啥问题导致的
> 
> 经测试，目前暂未发现antdocs主题存在该类问题，您可以检查看看是否有其他工具影响antdocs占用升高~

测出问题了，是homebadge插件导致的

**Comment by zpfz** [comment]
> > > 谷歌浏览器Firefox自带的问题，内存占用一直都一样，高达8个左右也不知道是啥问题导致的
> > 
> > 经测试，目前暂未发现antdocs主题存在该类问题，您可以检查看看是否有其他工具影响antdocs占用升高~
> 
> 测出问题了，是homebadge插件导致的

😰唉，小丑🤡竟然是我自己…
