### ISSUE TITLE
theorem right 语法支持

### ISSUE THREAD

**Issue by lunxian8** [zpfz/vuepress-theme-antdocs#37]
::: theorem 牛顿第一定律
假若施加于某物体的外力为零，则该物体的运动速度不变。

::: right
来自 [维基百科](https://zh.wikipedia.org/wiki/%E7%89%9B%E9%A1%BF%E8%BF%90%E5%8A%A8%E5%AE%9A%E5%BE%8B)
:::

![image](https://user-images.githubusercontent.com/27261113/122498114-1f25c800-d021-11eb-8729-81e300fb7fb3.png)

**Comment by zpfz** [comment]
你指的是哪种语法支持呢？

**Comment by lunxian8** [comment]
> 你指的是哪种语法支持呢？
实现如图这样的效果
抱歉，这应该称呼一种语法还是标签？

::: theorem 牛顿第一定律
假若施加于某物体的外力为零，则该物体的运动速度不变。

::: right
来自 维基百科
:::

**Comment by zpfz** [comment]
这个功能需要利用 VuePress 自定义容器功能，详情见：[vuepress-plugin-container](https://vuepress-community.netlify.app/en/plugins/container/#usage)

**Comment by lunxian8** [comment]
> vuepress-plugin-container
谢谢
