### ISSUE TITLE
内容区域分栏怎么实现呢？

### ISSUE THREAD

**Issue by yanjiaoguang** [zpfz/vuepress-theme-antdocs#38]
例如这个文档：https://www.uviewui.com/components/install.html

**Comment by zpfz** [comment]
大概思路：把主题copy到对应的theme下，建一个全局组件作为右侧大纲栏，然后把这个组件放入Page.vue内，然后写对应的大纲显示逻辑，再优化下媒体查询显示效果。

**Comment by yanjiaoguang** [comment]
> 大概思路：把主题copy到对应的theme下，建一个全局组件作为右侧大纲栏，然后把这个组件放入Page.vue内，然后写对应的大纲显示逻辑，再优化下媒体查询显示效果。

好的，谢谢你
