### ISSUE TITLE
在style.less内不能覆盖原有样式

### ISSUE THREAD

**Issue by Jikexiaobai** [zpfz/vuepress-theme-antdocs#39]
我在.vuepress/styles/style.less文件内编写样式
执行yarn docs:dev后
发现并不能覆盖原有的样式，我需要在哪里编写样式才可以覆盖原有样式。

**Comment by Jikexiaobai** [comment]
我的vuepress版本为：1.8.2
antdocs主题版本为1.3.5

**Comment by zpfz** [comment]
> 我在.vuepress/styles/style.less文件内编写样式
> 执行yarn docs:dev后
> 发现并不能覆盖原有的样式，我需要在哪里编写样式才可以覆盖原有样式。
> 
> 

不能覆盖原有样式的原因可能是样式优先级出现冲突，请确认下是否是这个原因导致的。
