### ISSUE TITLE
core.js 3.x 报错

### ISSUE THREAD

**Issue by XiaoMuCOOL** [zpfz/vuepress-theme-antdocs#4]
使用core.js 3.6.5,Vuepress可以正常跑起来，改变主题为antdocs后运行报错。

**Comment by zpfz** [comment]
请不要更新最新版本的 core.js，antdocs主题默认用的 2.x 版本的 core.js，这也是为了兼容处理。

**Comment by XiaoMuCOOL** [comment]
不是啊，大神，最新版vue-cli 默认安装core.js 3.X，我改成core.js 2.X 项目就运行不起来了。。。
