### ISSUE TITLE
进入多级目录的文档,顶部 nav 的激活高亮有问题

### ISSUE THREAD

**Issue by GallenHu** [zpfz/vuepress-theme-antdocs#40]
**Describe the bug**
我的文档位于 `docs/document/category1/doc1.md`
设置了顶部 Nav:
```
nav: [
      { text: "文档", link: "/document/", }
]
```

进入 `domain.com/document/category1/doc1.html` 页面时 nav 没有激活高亮

**To Reproduce**
同描述

**Expected behavior**
文档（/document/）导航菜单激活高亮

**System Info**
- VuePress version: 1.8.2
- Antdocs version: 1.3.5
- Node version: 14.17.2
- OS version: OSX 11

**Additional context**

看源码打印了 [currentPage](https://github.com/zpfz/vuepress-theme-antdocs/blob/master/components/NavLinks.vue#L105) 和 `a-menu` 的 [key](https://github.com/zpfz/vuepress-theme-antdocs/blob/master/components/NavLinks.vue#L73) 分别是 currentPage="/document/category1/"   key = /document/   所以被认为未选中激活了

**Comment by zpfz** [comment]
目前激活导航栏菜单的条件比较苛刻（目录层级关系参照官方源文档），后期再考虑有无更好的解决方案。

**Comment by guihua** [comment]
我也遇到了这个问题，左侧多级目录切换后，顶部导航消失了

**Comment by zpfz** [comment]
AntDocs v1.4.3 已优化这问题，欢迎更新😃
