### ISSUE TITLE
Cannot read properties of undefined (reading 'getState')

### ISSUE THREAD

**Issue by xuebigshuai** [zpfz/vuepress-theme-antdocs#42]
**Describe the bug**
启动工程后，报一堆路由问题，但是能正常使用
![image](https://user-images.githubusercontent.com/22486789/131993302-9554585a-a8dc-4aca-a862-9620e2217c14.png)

**Comment by xuebigshuai** [comment]
![image](https://user-images.githubusercontent.com/22486789/131993394-795578dc-6709-4011-b63f-ff54488dbfee.png)

**Comment by xuebigshuai** [comment]
![image](https://user-images.githubusercontent.com/22486789/131993512-d3cc8560-265a-4294-b93f-8dff63c32aa2.png)

**Comment by zpfz** [comment]
请检查侧边栏配置是否正确，或者加群867711329跟进问题
