### ISSUE TITLE
Vue.mixin({ store}) 无法覆盖该主题自带的 vuex

### ISSUE THREAD

**Issue by tanglaoji** [zpfz/vuepress-theme-antdocs#43]
默认主题引入 vuex 的方式是 Vue.mixin({ store})，但使用了该主题后，不能覆盖，只能使用模块动态注册来代替

**Comment by tanglaoji** [comment]
[issue](https://github.com/vuejs/vuepress/issues/1514)<br/>[模块动态注册](https://v3.vuex.vuejs.org/zh/guide/modules.html#%E6%A8%A1%E5%9D%97%E5%8A%A8%E6%80%81%E6%B3%A8%E5%86%8C)

**Comment by zpfz** [comment]
> 默认主题引入 vuex 的方式是 Vue.mixin({ store})，但使用了该主题后，不能覆盖，只能使用模块动态注册来代替

试试把 store 换成其他不冲突的名称试试？

**Comment by tanglaoji** [comment]
已经收到你的邮件，我会尽快回复！

**Comment by tanglaoji** [comment]
已经收到你的邮件，我会尽快回复！
