### ISSUE TITLE
考虑扩展为vitepress的主题吗

### ISSUE THREAD

**Issue by mosuzi** [zpfz/vuepress-theme-antdocs#44]
我发现这个主题看起来还不错，没那么多花里胡哨，考虑支持一下vitepress吗，因为比起启动速度，vite比webpack确实快太多了

**Comment by zpfz** [comment]
> 我发现这个主题看起来还不错，没那么多花里胡哨，考虑支持一下vitepress吗，因为比起启动速度，vite比webpack确实快太多了

目前没有计划。毕竟 vuepress 2.x 也支持 vite，另外，antdocs 下个版本应该会换其他 ui 库。
