### ISSUE TITLE
希望添加文章标题目录

### ISSUE THREAD

**Issue by Baikeryoyo** [zpfz/vuepress-theme-antdocs#46]
文章标题目录集成在侧边栏，用户可以通过点击文章内的目录快速跳转文章内的位置
但是侧边栏的内容是一个分类下的所有文章目录
可以在侧边栏内增加类似目录的前进后退
大概找了一下，类似vdoing主题的侧边栏效果
https://github.com/xugaoyi/vuepress-theme-vdoing
![image](https://user-images.githubusercontent.com/57838797/165915795-ead015bb-8886-4582-a61d-65e07cdc36d0.png)
![image](https://user-images.githubusercontent.com/57838797/165915858-cf67ba16-30e7-4628-bf8d-697e902b789e.png)

**Comment by zpfz** [comment]
除了面包屑，其他功能是VP默认功能可以做到的吧

**Comment by Baikeryoyo** [comment]
> 除了面包屑，其他功能是VP默认功能可以做到的吧

？？？在哪里

**Comment by zpfz** [comment]
> > 除了面包屑，其他功能是VP默认功能可以做到的吧
> 
> ？？？在哪里

按逻辑处理好路径对应侧边栏就可以了

**Comment by Baikeryoyo** [comment]
> > > 除了面包屑，其他功能是VP默认功能可以做到的吧
> > 
> > 
> > ？？？在哪里
> 
> 按逻辑处理好路径对应侧边栏就可以了

这个侧边栏目录是文件目录啊，不是文件内标题的目录啊

**Comment by zpfz** [comment]
> 这个侧边栏目录是文件目录啊，不是文件内标题的目录啊

是不是这种效果？![demo.gif](https://s2.loli.net/2022/05/06/Wbm4tzli3u1MCan.gif)

**Comment by Baikeryoyo** [comment]
> > 这个侧边栏目录是文件目录啊，不是文件内标题的目录啊
> 
> 是不是这种效果？![demo.gif](https://camo.githubusercontent.com/53a848156e1df9f5851baa3266f3a3e43ba957fb536802ac52eff67ae8dad6b1/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f30362f57626d34747a6c693375314d43616e2e676966)

对，就是这种，我无法把一个md文档内的标题转换为图中的这种目录

**Comment by zpfz** [comment]
> 对，就是这种，我无法把一个md文档内的标题转换为图中的这种目录

你进一下交流群吧 -> [点击链接加入群聊【VuePress | VitePress 社区】](https://jq.qq.com/?_wv=1027&k=tx9Mwmmd)，我把项目发群文件，你再下载研究吧
