### ISSUE TITLE
请教为什么图片会生成俩次

### ISSUE THREAD

**Issue by 5279314** [zpfz/vuepress-theme-antdocs#48]
图片存放位置：
E:\xxxx\docs\.vuepress\public\img\
![image](https://user-images.githubusercontent.com/27267683/207814159-a6f056b5-0aea-43e7-a2fb-938e47614dcf.png)

通过yarn run docs:build 构建

会发现dict文件夹中存在俩个img图片位置
第一个位置
![image](https://user-images.githubusercontent.com/27267683/207815999-51a5f280-7e9e-4ab1-9f96-ed71d2070533.png)
第二个位置（实际网站只用到这个）
![image](https://user-images.githubusercontent.com/27267683/207816161-8b1fb28f-124a-41de-8ae4-2b3a0002fdc2.png)

请问如何让他图片只生成一次呢，图片太占用空间了

**Comment by zpfz** [comment]
根据 VuePress 官网说明的 build 资源文件出来的位置是 `.vuepress/public` → `.vuepress/dist`，所以 `.vuepress/public/img` → `.vuepress/dist/img`。Antdocs 默认不用其他图片资源情况下，build 后 dist 文件夹是会有这么一个 `assets/img` 文件夹，里面存放搜索框图标资源。为了统一资源存放位置，你图片资源在 `.vuepress/public` 的位置应该为 `.vuepress/public/assets/img`，并且每次 build 请确认 dist 下的内容都是重新生成的。
