### ISSUE TITLE
导航栏配置 `target="_blank"` 和官方的主题行为不一致。

### ISSUE THREAD

**Issue by crazywhalecc** [zpfz/vuepress-theme-antdocs#49]
**Describe the bug**
导航栏配置 `target="_blank"` 和官方的仓库行为不一致。

**To Reproduce**
```js
module.exports = {
    themeConfig: {
        nav: [{ text: 'API', link: '/doxy/index.html', target:'_blank' }]
    }
}
```

**Expected behavior**
应该在新页面打开，而且该导航栏应该被当作 External Link。

**System Info**
- VuePress version: 1.9.7
- Antdocs version: latest version (github main branch)
- Node version: v19.2.0
- OS version: macOS 12.6.2

**Additional context**
相关代码可能如下：https://github.com/vuejs/vuepress/blob/38e98634af117f83b6a32c8ff42488d91b66f663/packages/%40vuepress/theme-default/components/NavLink.vue#L57

https://github.com/zpfz/vuepress-theme-antdocs/blob/5303fdecd47552659be44b0386a07bfe5c6d0176/components/NavLinks.vue#L120

**Comment by zpfz** [comment]
您提的 issue 已知悉，预计下个版号优化该问题，感谢您的反馈～

**Comment by zpfz** [comment]
AntDocs v1.4.6 已优化该问题，详情见：[v1.4.6](https://antdocs.js.org/guide/changelog.html)
