### ISSUE TITLE
运行报  Cannot find module 'core-js/library/fn/object/define-property', 什么情况

### ISSUE THREAD

**Issue by wangyanqisky** [zpfz/vuepress-theme-antdocs#5]
<img width="1259" alt="屏幕快照 2020-05-09 上午11 40 44" src="https://user-images.githubusercontent.com/19618476/81463173-fdd19600-91e9-11ea-8004-b03c2af879cb.png">

"vuepress": "^1.4.1",
"vuepress-theme-antdocs": "^1.0.1"
node: 10.13.0

**Comment by zpfz** [comment]
请确认core-js是否冲突，可以加群867711329进一步提交问题，谢谢~

**Comment by calebman** [comment]
我也报了这个错，是因为 `core-js 3.x` 版本的`api` 变动导致的，降低版本到 2.x 即可，其实也就是作者说的版本冲突问题。

**Comment by changshunxu520** [comment]
如何降级呢？

**Comment by calebman** [comment]
> 如何降级呢？

package.json 中引用 core-js 的版本修改成 2.x，然后重新 npm i 即可

**Comment by zpfz** [comment]
> 如何降级呢？

具体解决方案见上方，谢谢~

**Comment by jingping-ye** [comment]
碰到相同问题了，有不降级`core.js`的解决方案吗？

**Comment by zpfz** [comment]
> 碰到相同问题了，有不降级`core.js`的解决方案吗？

正常情况下，主题已经对 core-js 依赖进行降级处理。如果你的项目自行添加了 core-js 依赖，请确保 core-js 版本为 2.x 版本，如果仅仅设置主题后出现该错误，建议删除 node_module 、package-lock.json（若有） 、yarn.lock（若有）相关文件（夹），然后重新 yarn install（推荐）。如果还不能解决问题，可以加群867711329进一步反馈问题，谢谢~

**Comment by cyt68** [comment]
注意降级版本不对可能还是会报错，2.6.11试试

**Comment by bulolo** [comment]
看了半天还是不知道怎么降级。🎎

**Comment by zpfz** [comment]
> 看了半天还是不知道怎么降级。🎎

yarn upgrade core-js@^2.6.11

**Comment by cyt68** [comment]
升级了core-js的可以在config.json中加个别名试一下。
chainWebpack (config) {
   config.resolve.alias.set('core-js/library/fn', 'core-js/features');
}

**Comment by cyt68** [comment]
> 碰到相同问题了，有不降级`core.js`的解决方案吗？

升级了core-js的可以在config.json中加个别名试一下。
chainWebpack (config) {
config.resolve.alias.set('core-js/library/fn', 'core-js/features');
}

**Comment by WindyNanzi** [comment]
> 升级了core-js的可以在config.js中加个别名试一下。
> chainWebpack (config) {
> config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> }

---
大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
[issues链接](https://github.com/zloirock/core-js/issues/837)
![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)

但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`

**Comment by cyt68** [comment]
> > 升级了core-js的可以在config.js中加个别名试一下。
> > chainWebpack (config) {
> > config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> > }
> 
> 大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
> [issues链接](https://github.com/zloirock/core-js/issues/837)
> ![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)
> 
> 但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`

也没啥，对比下2.*和3.*的core-js源码目录结构发现的，其实我也不能保证完全覆盖，但是理论上开发者应该是会在新版本保留旧函数的，不然兼容性太差了，只是换了个文件夹而已，而且暂时这么别名修改也没有发现问题。

**Comment by WindyNanzi** [comment]
> > > 升级了core-js的可以在config.js中加个别名试一下。
> > > chainWebpack (config) {
> > > config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> > > }
> > 
> > 
> > 大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
> > [issues链接](https://github.com/zloirock/core-js/issues/837)
> > ![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)
> > 但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`
> 
> 也没啥，对比下2.*和3.*的core-js源码目录结构发现的，其实我也不能保证完全覆盖，但是理论上开发者应该是会在新版本保留旧函数的，不然兼容性太差了，只是换了个文件夹而已，而且暂时这么别名修改也没有发现问题。

厉害👍，依据我上文中提到的 issues, 我发现`yarn add -D @babel/runtime-corejs2` 也是可行的，究其原因，应该是安装 `ant-design-vue`依赖之后，`babel-runtime` 的 `core-js`版本低了，和 `vuepress` 依赖的 `core-js`版本不兼容：
![image](https://user-images.githubusercontent.com/39194294/111566428-192d0a80-87d8-11eb-815b-54fddfe6dca9.png)
![image](https://user-images.githubusercontent.com/39194294/111566453-277b2680-87d8-11eb-8bfb-5814e56c2a51.png)

**Comment by cyt68** [comment]
> > > > 升级了core-js的可以在config.js中加个别名试一下。
> > > > chainWebpack (config) {
> > > > config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> > > > }
> > > 
> > > 
> > > 大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
> > > [issues链接](https://github.com/zloirock/core-js/issues/837)
> > > ![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)
> > > 但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`
> > 
> > 
> > 也没啥，对比下2.*和3.*的core-js源码目录结构发现的，其实我也不能保证完全覆盖，但是理论上开发者应该是会在新版本保留旧函数的，不然兼容性太差了，只是换了个文件夹而已，而且暂时这么别名修改也没有发现问题。
> 
> 厉害👍，依据我上文中提到的 issues, 我发现`yarn add -D @babel/runtime-corejs2` 也是可行的，究其原因，应该是安装 `ant-design-vue`依赖之后，`babel-runtime` 的 `core-js`版本低了，和 `vuepress` 依赖的 `core-js`版本不兼容：
> ![image](https://user-images.githubusercontent.com/39194294/111566428-192d0a80-87d8-11eb-815b-54fddfe6dca9.png)
> ![image](https://user-images.githubusercontent.com/39194294/111566453-277b2680-87d8-11eb-8bfb-5814e56c2a51.png)

- 

- 

> > > > 升级了core-js的可以在config.js中加个别名试一下。
> > > > chainWebpack (config) {
> > > > config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> > > > }
> > > 
> > > 
> > > 大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
> > > [issues链接](https://github.com/zloirock/core-js/issues/837)
> > > ![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)
> > > 但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`
> > 
> > 
> > 也没啥，对比下2.*和3.*的core-js源码目录结构发现的，其实我也不能保证完全覆盖，但是理论上开发者应该是会在新版本保留旧函数的，不然兼容性太差了，只是换了个文件夹而已，而且暂时这么别名修改也没有发现问题。
> 
> 厉害👍，依据我上文中提到的 issues, 我发现`yarn add -D @babel/runtime-corejs2` 也是可行的，究其原因，应该是安装 `ant-design-vue`依赖之后，`babel-runtime` 的 `core-js`版本低了，和 `vuepress` 依赖的 `core-js`版本不兼容：
> ![image](https://user-images.githubusercontent.com/39194294/111566428-192d0a80-87d8-11eb-815b-54fddfe6dca9.png)
> ![image](https://user-images.githubusercontent.com/39194294/111566453-277b2680-87d8-11eb-8bfb-5814e56c2a51.png)



> > > > 升级了core-js的可以在config.js中加个别名试一下。
> > > > chainWebpack (config) {
> > > > config.resolve.alias.set('core-js/library/fn', 'core-js/features');
> > > > }
> > > 
> > > 
> > > 大神厉害👍，想请教您是怎么定位到这个问题并解决的呢？我在 core-js 的 github issues 中发现了和这个很类似的提问：
> > > [issues链接](https://github.com/zloirock/core-js/issues/837)
> > > ![image](https://user-images.githubusercontent.com/39194294/111559309-37d8d480-87cb-11eb-9fb0-5c76732c20ff.png)
> > > 但是解决方案是怎么思索出来的？😂从何处下结论是这样解决的呢？ `core-js/library/fn` => `core-js/features`
> > 
> > 
> > 也没啥，对比下2.*和3.*的core-js源码目录结构发现的，其实我也不能保证完全覆盖，但是理论上开发者应该是会在新版本保留旧函数的，不然兼容性太差了，只是换了个文件夹而已，而且暂时这么别名修改也没有发现问题。
> 
> 厉害👍，依据我上文中提到的 issues, 我发现`yarn add -D @babel/runtime-corejs2` 也是可行的，究其原因，应该是安装 `ant-design-vue`依赖之后，`babel-runtime` 的 `core-js`版本低了，和 `vuepress` 依赖的 `core-js`版本不兼容：
> ![image](https://user-images.githubusercontent.com/39194294/111566428-192d0a80-87d8-11eb-815b-54fddfe6dca9.png)
> ![image](https://user-images.githubusercontent.com/39194294/111566453-277b2680-87d8-11eb-8bfb-5814e56c2a51.png)

👍 你的分析也很对，其实就是版本不一致，这个主题没有去支持新版core-js

**Comment by zpfz** [comment]
AntDocs v1.3.2 已修复这个问题，具体见：[v1.3.2](https://antdocs.vercel.app/guide/changelog.html)
